variable "tenancy_ocid" {}
variable "compartment_id" {}
variable "root_compartment_id" {}
variable "region" {}
variable "registry" {}
variable "application_name" {}
variable "vault_ocid" {}
variable "vault_key_ocid" {}
variable "bucket_namespace" {}